apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: l6u3wol24-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l6u3wol24-nodejs 
  name: l6u3wol24-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: l6u3wol24-nodejs 
